#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <list>
#include <deque>
#include <iterator>
#include <algorithm>
#include <fstream>
#include <chrono>
#include <sstream>

using std::cout;
using std::cin;
using std::string;
using std::endl;
using std::vector;
using std::list;
using std::deque;
using std::stringstream;
using std::to_string;
